
Exercises XP Gold

Last Updated: November 20th, 2024

👩‍🏫 👩🏿‍🏫 What You’ll learn

    Advanced techniques in NumPy for handling random arrays, matrix normalization, and array spacing.
    Skills in finding minimum, maximum, and performing normalization on matrices.


🛠️ What you will create

    Advanced NumPy arrays, including a 5x5 array with random values, a normalized 3x3 matrix, and evenly spaced elements in an array.


Brief Introduction to Matrices

What is a Matrix in Python and NumPy?

    A matrix is a two-dimensional array of numbers arranged in rows and columns. In Python, matrices can be represented using lists of lists or more efficiently with NumPy arrays.
    NumPy provides a powerful and efficient way to work with matrices, offering various functions for matrix operations.

Matrix Example:


# Example of a 3x3 matrix using NumPy
import numpy as np
matrix_example = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix_example)


Note: We will cover these topics in more depth in the next day’s lesson.




In [2]:
import numpy as np
from PIL import Image
print(np.__version__)

2.3.1


In [4]:
arr = np.random.rand(5, 5)
min_val = arr.min()
max_val = arr.max()
print(arr)
print("Min:", round(min_val, 2), "Max:", round(max_val, 2))

[[0.44285705 0.5364224  0.66363584 0.90331886 0.4172723 ]
 [0.94982251 0.89771759 0.46272011 0.21363811 0.62758673]
 [0.45493491 0.70304153 0.37766907 0.40100393 0.3891219 ]
 [0.41988505 0.18911838 0.29331743 0.20416989 0.64169241]
 [0.92827159 0.7157556  0.6226617  0.84301738 0.02299662]]
Min: 0.02 Max: 0.95


In [6]:
matrix = np.random.rand(3, 3)
print(matrix)
print("\n")
mean = matrix.mean()
print(mean)
print("\n")
std = matrix.std()
print(std)
print("\n")
normalized = (matrix - mean) / std

print(normalized)

[[0.05801114 0.59428768 0.75183638]
 [0.81787698 0.9817664  0.49068586]
 [0.39421687 0.13462828 0.64511802]]


0.5409364005969867


0.2889753897848937


[[-1.67116398  0.18462222  0.72981986]
 [ 0.95835352  1.52549322 -0.17389211]
 [-0.50772329 -1.40603019  0.36052075]]


In [13]:
arr = np.linspace(0, 10, 50, endpoint=False)
print(arr) 

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.
 7.2 7.4 7.6 7.8 8.  8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]


In [ ]:
A = np.random.randint(0, 10, size=(5, 3))
B = np.random.randint(0, 10, size=(3, 2))

print("Matrice A :")
print(A)
print("\nMatrice B :")
print(B)

result = np.dot(A, B)

print("\nRésultat A · B :")
print(result)

# Chaque ligne de A avec chaque colonne de B

Matrice A :
[[8 0 9]
 [5 8 6]
 [0 9 9]
 [4 0 3]
 [7 5 1]]

Matrice B :
[[8 4]
 [3 7]
 [2 1]]

Résultat A · B :
[[82 41]
 [76 82]
 [45 72]
 [38 19]
 [73 64]]


In [21]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [1, 3, 5],
              [2, 4, 6]])

B = np.array([[1, 2],
              [0, 1],
              [4, 0]])

result = np.dot(A,B)
print(result)

[[13  4]
 [28 13]
 [43 22]
 [21  5]
 [26  8]]
