
Exercises XP

Last Updated: March 7th, 2025

What You Will Learn:

    Core NumPy operations including array creation, manipulation, and basic array operations.
    Skills in handling one-dimensional and multi-dimensional arrays.


What You Will Create:

    A series of NumPy arrays demonstrating different operations, ranging from simple array creation to more complex manipulations.


🌟 Exercise 1 : Array Creation and Manipulation
Instructions

Create a 1D NumPy array containing numbers from 0 to 9.

Expected Output:


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


🌟 Exercise 2 : Type Conversion and Array Operations
Instructions

Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

Expected Output:


array([3, 2, 0, 1, 2])


🌟 Exercise 3 : Working with Multi-Dimensional Arrays
Instructions

Create a 3x3 NumPy array with values ranging from 1 to 9.

Expected Output:


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
Instructions

Create a 2D NumPy array of shape (4, 5) filled with random numbers.

Expected Output:


array([[0.56, 0.85, 0.01, 0.42, 0.68],
       [0.22, 0.37, 0.73, 0.93, 0.39],
       [0.44, 0.03, 0.87, 0.02, 0.83],
       [0.78, 0.87, 0.98, 0.80, 0.46]])


🌟 Exercise 5 : Indexing Arrays
Instructions

Select the second row from a given 2D NumPy array.

Expected Output:


array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])


🌟 Exercise 6 : Reversing elements
Instructions

Reverse the order of elements in a given 1D NumPy array (first element becomes last).

Expected Output:


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])


🌟 Exercise 7 : Identity Matrix
Instructions

Create a 4x4 identity matrix using NumPy.

Expected Output:


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])


🌟 Exercise 8 : Simple Aggregate Funcs
Instructions

Find the sum and average of a given 1D array.

Expected Output:


Sum: 45, Average: 4.5


🌟 Exercise 9 : Create Array and Change its Structure
Instructions

Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

Expected Output:


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])


🌟 Exercise 10 : Conditional Selection of Values
Instructions

Extract all odd numbers from a given NumPy array.

Expected Output:


array([1, 3, 5, 7, 9])


In [2]:
import numpy as np
from PIL import Image
print(np.__version__)

2.3.1


In [3]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
listA = [3.14, 2.17, 0, 1, 2]

arrayF = np.array(listA, dtype=float)

print(arrayF)
print("Data type:", arrayF.dtype)

[3.14 2.17 0.   1.   2.  ]
Data type: float64


In [ ]:
array3d = np.arange(1,10).reshape(3,3)
print(array3d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
randArry = np.random.random(size=(4, 5))
print(randArry )

[[0.4457972  0.82857024 0.10644091 0.1430334  0.14613213]
 [0.34987419 0.93421517 0.9263239  0.19775476 0.31877831]
 [0.73807265 0.67793494 0.88629629 0.00736222 0.00666193]
 [0.56813494 0.34444613 0.09300387 0.14279319 0.66726568]]


In [15]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
print(array[1:2])
print(array[1])

[[20 21 22 23 24]]
[20 21 22 23 24]


In [16]:
array = np.arange(10)
reversed_array = array[::-1]

print(reversed_array)

[9 8 7 6 5 4 3 2 1 0]


In [22]:
array = np.arange(16).reshape(4, 4)
array[:] = 0 
indices = np.arange(4)
array[indices, indices] = 1

print(array)

# Meilleur methode : 

array = np.zeros((4, 4))
indices = np.arange(4)
array[indices, indices] = 1

print(array)

#Methode opti

identity_matrix = np.eye(4)
print(identity_matrix)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
array = np.arange(10)
arraySum = np.sum(array)
arrrayAvg = np.average(array)
print(arraySum)
print(arrrayAvg)


45
4.5


In [24]:
array = np.arange(1, 21).reshape(4, 5)
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [25]:
array = np.arange(10)
odd_numbers = array[array % 2 == 1]

print(odd_numbers)

[1 3 5 7 9]
