
Exercises XP Ninja

Last Updated: November 20th, 2024

👩‍🏫 👩🏿‍🏫 What You’ll learn

    How to manipulate matrices and find commonalities in data sets using NumPy.
    Advanced array operations like maximum value replacement and common value identification.


🛠️ What you will create

    A set of challenging exercises that include replacing the maximum value in a matrix and finding common values between arrays.


Exercise 1 : Maximum Value Replacement in Matrix
Instructions

Create a random 5x5 matrix and replace the maximum value by 0.

Expected Output:


array([[0.23, 0.35, 0.01, 0.05, 0.11],
       [0.91, 0.28, 0.66, 0.13, 0.14],
       [0.94, 0.40, 0.76, 0.65, 0.46],
       [0.12, 0.15, 0.95, 0.57, 0.60],
       [0.17, 0.97, 0.87, 0.45, 0.  ]])


Exercise 2 : Finding Common Values in Arrays
Instructions

Find the common values between two random arrays of size 5.

Expected Output:


array([0.35, 0.66, 0.76])


Exercise 3 : Sorting Array in Ascending and Descending Order
Instructions

Create a random 1D array of size 10 and sort it in ascending and then in descending order.

Expected Output:


Ascending: array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])
Descending: array([1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1])


Brief Introduction to Matrix Rank

What is Matrix Rank?

    The rank of a matrix indicates the number of linearly independent rows or columns in the matrix.
    For example, in a matrix with rows [1, 2, 3] and [2, 4, 6], the second row is just twice the first, so these two rows are not independent. This matrix would have a rank of 1.

Why and When to Use Matrix Rank?

    Matrix rank is used to determine if a set of vectors (rows or columns) are linearly independent. This is crucial in understanding the solutions to systems of linear equations represented by the matrix.
    In simpler terms, it helps in identifying if the given matrix has redundant information or not.


Exercise 4 : Matrix Rank Determination
Instructions

Generate a random 4x4 matrix and find the rank of the matrix.

Expected Output:


Rank: 4


Exercise 5 : Creating Border Array
Instructions

Create a 2D array with 1 on the border and 0 inside.

Expected Output:


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])


In [1]:
import numpy as np
from PIL import Image
print(np.__version__)

2.3.1


In [3]:
matrix = np.random.rand(5, 5)
max_index = np.unravel_index(np.argmax(matrix), matrix.shape)
matrix[max_index] = 0

print("\n", matrix)


 [[0.77443443 0.9093012  0.04218225 0.08191483 0.6766436 ]
 [0.77381222 0.48738641 0.77486649 0.61229029 0.21460546]
 [0.95910013 0.52915998 0.28838061 0.61406255 0.        ]
 [0.30921394 0.24916518 0.94427893 0.79769936 0.91282257]
 [0.17631076 0.60379166 0.23298379 0.05991822 0.49205985]]


In [10]:
arr1 = np.random.randint(0, 10, size=(12))
arr2 = np.random.randint(0, 10, size=(12))
print(arr1)
print(arr2)
common = np.intersect1d(arr1,arr2)

print(common)

[8 7 5 9 6 8 9 2 1 5 5 4]
[0 4 4 6 4 8 3 0 3 6 0 9]
[4 6 8 9]


In [11]:
arr = np.round(np.random.rand(10), 2)
asc = np.sort(arr)
desc = asc[::-1]

print("Ascending :", asc)
print("Descending:", desc)

Ascending : [0.01 0.02 0.38 0.56 0.58 0.62 0.67 0.69 0.7  0.75]
Descending: [0.75 0.7  0.69 0.67 0.62 0.58 0.56 0.38 0.02 0.01]


In [12]:
mat = np.random.rand(4, 4)
rank = np.linalg.matrix_rank(mat)

print("Rank :", rank)

Rank : 4


In [2]:
border_array = np.zeros((5, 5), dtype=int)

border_array[0, :] = 1
border_array[-1, :] = 1
border_array[:, 0] = 1
border_array[:, -1] = 1

print(border_array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
