In [56]:
import numpy as np
from PIL import Image
print(np.__version__)

2.3.0


In [2]:

# Create a simple array
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

[1 2 3 4 5]


In [3]:
# Creating a 1D NumPy array
array_1d = np.array([1, 2, 3, 4])
print("1D Array:", array_1d)  # Expected Output: 1D Array: [1 2 3 4]

# Creating a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)
# Expected Output:
# 2D Array:
# [[1 2 3]
#  [4 5 6]]

# Array attributes
print("Shape:", array_2d.shape)  # Expected Output: Shape: (2, 3) - 2 rows and 3 columns
print("Size:", array_2d.size)   # Expected Output: Size: 6 - Total 6 elements
print("Data Type:", array_2d.dtype)  # Expected Output: Data Type: int64 (or similar, depending on system)

1D Array: [1 2 3 4]
2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data Type: int64


In [4]:
# Array attributes
print("Shape:", array_2d.shape)  # Expected Output: Shape: (2, 3) - 2 rows and 3 columns
print("Size:", array_2d.size)   # Expected Output: Size: 6 - Total 6 elements
print("Data Type:", array_2d.dtype)  # Expected Output: Data Type: int64 (or similar, depending on system)


Shape: (2, 3)
Size: 6
Data Type: int64


In [5]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# Output:
# 3D Array: 
# [[[1 2]
#   [3 4]]
#
#  [[5 6]
#   [7 8]]]
# Shape: (2, 2, 2), Size: 8

In [ ]:
array_2d_large = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# Output:
# Larger 2D Array: 
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
# Shape: (3, 4), Size: 12



1. Create Arrays: Create a 1D array with numbers from 1 to 5 and a 2D array with numbers from 1 to 6 (reshape it to have 2 rows and 3 columns).

USE:(https://numpy.org/doc/stable/reference/generated/numpy.reshape.html), (https://numpy.org/doc/stable/reference/generated/numpy.arange.html)

2. Inspect Attributes: For each array you created, print its shape, size, and data type.

3. Play with Data Types: Create a new array with numbers from 1 to 3, but specify the data type as float. Check and print its data type.

Expected Output:

    Prints of the created arrays with their respective shapes, sizes, and data types.
    An array with a specified data type different from the default.


Exercise: Create the following arrays:

    A one dimensional array with the temperatures from this week.
    A two dimensional array of shape 2,5 with random values (choose them yourself) from 1 to 10.
    A 3D array with valid pixel values for a picture with 9 pixels.



In [11]:
array_1d = np.array([1, 2, 3, 4, 5])
print("Array 1D")
print(array_1d.shape)
print(array_1d.size)
print(array_1d.dtype)
print("\n")
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Array 2D")
print(array_2d.shape)
print(array_2d.size)
print(array_2d.dtype)
print("\n")
array_2d.reshape(2,3)
print("Array 2D")
print(array_2d.shape)
print(array_2d.size)
print(array_2d.dtype)
print("\n")
arr = np.array([1, 2, 3], dtype=float)
print("arr")
print(arr.shape)
print(arr.size)
print(arr.dtype)


Array 1D
(5,)
5
int64


Array 2D
(2, 3)
6
int64


Array 2D
(2, 3)
6
int64


arr
(3,)
3
float64


In [12]:
# 1D array
array_1d = np.arange(1, 6)
# 2D array
array_2d = np.arange(1, 7).reshape(2, 3)
# Attributes of the 1D array
print("1D Array:")
print("Array:", array_1d)
print("Shape:", array_1d.shape)
print("Size:", array_1d.size)
print("Data type:", array_1d.dtype)
# Attributes of the 2D array
print("\n2D Array:")
print("Array:\n", array_2d)
print("Shape:", array_2d.shape)
print("Size:", array_2d.size)
print("Data type:", array_2d.dtype)
# Array with specified data type
array_float = np.arange(1, 4, dtype=float)
print("\nArray with float data type:")
print("Array:", array_float)
print("Data type:", array_float.dtype)











1D Array:
Array: [1 2 3 4 5]
Shape: (5,)
Size: 5
Data type: int64

2D Array:
Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data type: int64

Array with float data type:
Array: [1. 2. 3.]
Data type: float64


In [ ]:
# 1. Températures (1D float, 7 valeurs)
temperatures = np.arange(20.5, 27.5, 1.0)  # Donne 7 valeurs
# ou : np.arange(7) + 20.0

# 2. Tableau 2D (2, 5) avec valeurs 1 à 10
valeurs_2d = np.arange(1, 11).reshape(2, 5)

# 3. Tableau 3D (3, 3, 3) avec des valeurs de 0 à 255 (RGB)
pixels = np.arange(27).reshape(3, 3, 3) * 9
pixels = pixels.astype(np.uint8)

# Affichage
print("Températures (1D):", temperatures)
print("Tableau 2D:\n", valeurs_2d)
print("Pixels (3D):\n", pixels)

Températures (1D): [20.5 21.5 22.5 23.5 24.5 25.5 26.5]
Tableau 2D:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Pixels (3D):
 [[[  0   9  18]
  [ 27  36  45]
  [ 54  63  72]]

 [[ 81  90  99]
  [108 117 126]
  [135 144 153]]

 [[162 171 180]
  [189 198 207]
  [216 225 234]]]


In [15]:

# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing a single element
print("Element at row 1, column 2:", array_2d[1, 2])  # Output: 6

# Accessing a row
print("Second row:", array_2d[1, :])  # Output: [4 5 6]

# Accessing a column
print("Third column:", array_2d[:, 2])  # Output: [3 6 9]

Element at row 1, column 2: 6
Second row: [4 5 6]
Third column: [3 6 9]


In [17]:

# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing a portion of the array
print("Slice of the array:", array_2d[0:2, 1:3])  # Output: [[2 3] [5 6]]


# Example array
array = np.array([[1, 2], [3, 4], [5, 6]])

# Boolean indexing
result = array[array > 3]
print("Result of Boolean Indexing:", result)  # Output: [4 5 6], a 1D array

# Creating a sample array
array = np.array([10, 20, 30, 40, 50])

# Indexing (accessing a single element)
print("First element:", array[0])

# Slicing (accessing multiple elements)
print("First three elements:", array[:3])

Slice of the array: [[2 3]
 [5 6]]
Result of Boolean Indexing: [4 5 6]
First element: 10
First three elements: [10 20 30]


Table for Indexing Types and Examples


Indexing Type 	1D Example 	2D Example 	3D Example
Single Index 	array_1d[2] 	array_2d[1, 0] 	array_3d[0, 1, 1]
Slice 	array_1d[1:3] 	array_2d[0:2, 1:3] 	array_3d[0, 1:3, 1:3]
Boolean Indexing 	array_1d[array_1d > 2] 	array_2d[array_2d % 2 == 0] 	array_3d[array_3d < 5]
Fancy Indexing 	array_1d[[0, 3]] 	array_2d[:, [1, 2]] 	array_3d[[0, 1], [1], [1]]


Exercise: Practicing Indexing and Slicing

1. Basic Indexing: Create an array of 10 elements and access the 5th element in it.

2. Basic Slicing: From the same array, extract a slice containing the 3rd to the 8th elements.

3. Boolean Indexing: Create an array of 6 random integers between 10 and 50. Print the elements that are greater than 30.

4. Fancy Indexing: From the same array, use fancy indexing to access the 2nd, 4th, and 6th elements.

Expected Output:

    The 5th element of the first array.
    A slice of the array showing elements from the 3rd to the 8th position.
    Elements greater than 30 from the random array.
    Selected elements (2nd, 4th, 6th) from the random array using fancy indexing.



In [ ]:
np_array=np.arange(10)
print(np_array)
print('\n')
print(np_array[4])
print("\n")
print(np_array[2:8])
print("\n")
#np.random.randint(10, 51, size=6)
array = np.arange(10, 60, 8)[:6]
print(array)
print(array[array > 30])
print("\n")
selected = array[[1, 3, 5]]
print(selected)


[0 1 2 3 4 5 6 7 8 9]


4


[2 3 4 5 6 7]


[10 18 26 34 42 50]
[34 42 50]


[18 34 50]


In [30]:
rand = np.random.randint(10, 50, 6)
print(rand[rand>30])

[42 33 38]


In [33]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
new = np.random.permutation(x)
print(new)

two = np.array([[1,2], [3,4], [5,6]])
np.random.permutation(two)
print(two)

[3 1 4 5 7 2 6]
[[1 2]
 [3 4]
 [5 6]]


In [35]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [36]:
arr = np.array([1, 2, 3, 4, 5])
arr[2] = 10  # Changing the third element
print(arr)  # Output: [1, 2, 10, 4, 5]

[ 1  2 10  4  5]


In [37]:
arr[1:4] = [20, 30, 40]
print(arr)  # Output: [1, 20, 30, 40, 5]

[ 1 20 30 40  5]


In [38]:
arr[arr > 10] = 100
print(arr)  # Output: [1, 100, 100, 100, 5]

[  1 100 100 100   5]


In [39]:
arr[np.array([1, 3])] = 500
print(arr)  # Output: [1, 500, 100, 500, 5]

[  1 500 100 500   5]


In [40]:
sub_arr = arr[1:3]
sub_arr[0] = 600
print(arr)  # Output: [1, 600, 100, 500, 5]

[  1 600 100 500   5]


In [41]:
a = np.arange(1, 11)
a[4] = 50

print("1. Array modifié :", a)

1. Array modifié : [ 1  2  3  4 50  6  7  8  9 10]


In [42]:
a = np.arange(10)
a[3:8] = -a[3:8]

print("2. Après modification :", a)

2. Après modification : [ 0  1  2 -3 -4 -5 -6 -7  8  9]


In [44]:
a = np.arange(5, 105, 5)[:20]
a[a > 50] = -1

print("3. Remplacement > 50 :", a)
b= np.random.randint(1, 100, size=20)
b[b > 50] = -1

print("3. Remplacement > 50 :", b)

3. Remplacement > 50 : [ 5 10 15 20 25 30 35 40 45 50 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
3. Remplacement > 50 : [-1 -1  9 -1 11 -1  8 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 31 33 28]


In [48]:
array = np.arange(25).reshape(5, 5)

indices = np.arange(5)
print(indices)
array[indices, indices] *= 2

print(array)

[0 1 2 3 4]
[[ 0  1  2  3  4]
 [ 5 12  7  8  9]
 [10 11 24 13 14]
 [15 16 17 36 19]
 [20 21 22 23 48]]


In [ ]:
a = np.arange(10)      # [0 1 2 3 4 5 6 7 8 9]
slice_view = a[2:5]    # [2 3 4] ← ceci est une *vue*, pas une copie
slice_view[0] = 99     # Modifie slice_view[0] = 99 → a[2] aussi !

print("5. Slice     :", slice_view)  # [99 3 4]
print("   Tableau a :", a)           # [0 1 99 3 4 5 6 7 8 9]
#utiliser copy pour une vraie copie

5. Slice     : [99  3  4]
   Tableau a : [ 0  1 99  3  4  5  6  7  8  9]


In [49]:
import numpy as np

# Creating sample arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
print("Addition:", a + b)

# Broadcasting
print("Broadcasting with scalar:", a * 3)

Addition: [5 7 9]
Broadcasting with scalar: [3 6 9]


In [50]:
# Creating a 1D array
a = np.array([1, 2, 3])

# Adding a scalar value to the array
result = a + 5

print("Original Array:", a)
print("After Adding 5:", result)

Original Array: [1 2 3]
After Adding 5: [6 7 8]


In [51]:
# Creating a 1D array and a 2D array
a = np.array([0, 1, 2])
b = np.array([[0, 1, 2], [3, 4, 5]])

# Adding the 1D array to each row of the 2D array
result = a + b

print("1D Array:", a)
print("2D Array:", b)
print("Broadcasted Addition:", result)

1D Array: [0 1 2]
2D Array: [[0 1 2]
 [3 4 5]]
Broadcasted Addition: [[0 2 4]
 [3 5 7]]


In [53]:
# Creating two arrays
a = np.array([[1], [2], [3]])
b = np.array([1, 2, 3])

# Adding the two arrays
result = a + b

print("Array a:", a)
print("Array b:", b)
print("Broadcasted Addition:", result)

Array a: [[1]
 [2]
 [3]]
Array b: [1 2 3]
Broadcasted Addition: [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [54]:
# Creating two incompatible arrays
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2])

try:
    result = a + b
except ValueError as e:
    print("Error:", e)

Error: operands could not be broadcast together with shapes (2,3) (2,) 


In [55]:
# Creating a 2D array and a 1D array
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])

# Element-wise multiplication
result = a * b

print("2D Array:", a)
print("1D Array:", b)
print("Broadcasted Multiplication:", result)

2D Array: [[1 2 3]
 [4 5 6]]
1D Array: [1 2 3]
Broadcasted Multiplication: [[ 1  4  9]
 [ 4 10 18]]


In [ ]:
image = Image.open('soldier.png', )
arr = np.array(image)
arr.shape
res = arr.mean(axis=2)
res = res.round()
res = res.astype(np.uint8)
im = Image.fromarray(res)
im.save('out.jpg')



1. Arithmetic Operations: Create two 1D arrays of 3 elements each and perform element-wise addition, subtraction, multiplication, and division.

2. Aggregation Functions: For the arrays created above, find the sum, mean, minimum, and maximum of each array.

3. Broadcasting with Scalar: Multiply one of the arrays by a scalar (e.g., 5) and observe the result.


In [57]:
a = np.array([2, 4, 6])
b = np.array([1, 2, 3])

# Opérations élément par élément
add = a + b
sub = a - b
mul = a * b
div = a / b  # division élément par élément

print("1. Addition     :", add)  # [3 6 9]
print("   Soustraction :", sub)  # [1 2 3]
print("   Multiplication:", mul) # [2 8 18]
print("   Division     :", div)  # [2. 2. 2.]

1. Addition     : [3 6 9]
   Soustraction : [1 2 3]
   Multiplication: [ 2  8 18]
   Division     : [2. 2. 2.]


In [58]:
print("\n2. Agrégations sur a :")
print("   Somme :", a.sum())
print("   Moyenne :", a.mean())
print("   Min :", a.min())
print("   Max :", a.max())

print("\n   Agrégations sur b :")
print("   Somme :", b.sum())
print("   Moyenne :", b.mean())
print("   Min :", b.min())
print("   Max :", b.max())


2. Agrégations sur a :
   Somme : 12
   Moyenne : 4.0
   Min : 2
   Max : 6

   Agrégations sur b :
   Somme : 6
   Moyenne : 2.0
   Min : 1
   Max : 3


In [59]:
broadcasted = a * 5

print("\n3. a * 5 =", broadcasted)  # [10 20 30]


3. a * 5 = [10 20 30]


In [60]:
# Creating a 1D array
array = np.arange(1, 10)  # Array of numbers from 1 to 9

# Reshaping to a 3x3 matrix
reshaped_array = array.reshape(3, 3)
print("Reshaped to 3x3:\n", reshaped_array)

Reshaped to 3x3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
transposed_array = reshaped_array.T
print("Transposed array:\n", transposed_array)

Transposed array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]




1. Reshape Array: Create a 1D array with 12 elements and reshape it to a 4x3 matrix. Then reshape it to a 2x6 matrix.

2. Transpose Matrix: Transpose the 2x6 matrix you created in the previous step.

3. Combine Reshaping and Transposing: Create a 3x4 matrix, transpose it, and then reshape the transposed matrix to a 1D array.


In [62]:
a = np.arange(12)  # [0, 1, 2, ..., 11]

reshape_4x3 = a.reshape(4, 3)
reshape_2x6 = a.reshape(2, 6)

print("1D array :", a)
print("4x3 matrix :\n", reshape_4x3)
print("2x6 matrix :\n", reshape_2x6)

1D array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
4x3 matrix :
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
2x6 matrix :
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [63]:
transpose_2x6 = reshape_2x6.T

print("Transpose of 2x6 (now 6x2):\n", transpose_2x6)

Transpose of 2x6 (now 6x2):
 [[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]


In [64]:
matrix_3x4 = np.arange(12).reshape(3, 4)

transposed = matrix_3x4.T            # devient 4x3
flattened = transposed.reshape(-1)   # devient 1D (avec -1 = auto-calcul)

print("3x4 matrix :\n", matrix_3x4)
print("Transposée (4x3) :\n", transposed)
print("Remise en 1D :", flattened)

3x4 matrix :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transposée (4x3) :
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Remise en 1D : [ 0  4  8  1  5  9  2  6 10  3  7 11]


In [66]:
# Reshaping data for machine learning model
data = np.arange(1, 101).reshape(20, 5)  # 20 samples, 5 features each
print(data)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]
 [ 26  27  28  29  30]
 [ 31  32  33  34  35]
 [ 36  37  38  39  40]
 [ 41  42  43  44  45]
 [ 46  47  48  49  50]
 [ 51  52  53  54  55]
 [ 56  57  58  59  60]
 [ 61  62  63  64  65]
 [ 66  67  68  69  70]
 [ 71  72  73  74  75]
 [ 76  77  78  79  80]
 [ 81  82  83  84  85]
 [ 86  87  88  89  90]
 [ 91  92  93  94  95]
 [ 96  97  98  99 100]]


In [69]:
# Preparing data for heatmap visualization
matrix = np.random.rand(10, 10)

reshaped_matrix = matrix.reshape(5, 20)  # Reshaping for a different visual representation
print(reshaped_matrix)

[[0.92470303 0.75818573 0.74782318 0.52548502 0.63553793 0.6315985
  0.89794861 0.71879894 0.37605147 0.96771413 0.16913282 0.67842165
  0.20132178 0.41562486 0.79905285 0.43736784 0.50075673 0.57254527
  0.9737007  0.6945872 ]
 [0.11191648 0.36583635 0.42757517 0.28263791 0.72887082 0.73792064
  0.42912429 0.13785472 0.75669986 0.73012476 0.26773451 0.86056785
  0.06403851 0.0739744  0.41579935 0.83587338 0.99113436 0.78981456
  0.35999036 0.10484019]
 [0.29511572 0.10583399 0.96466551 0.45368846 0.77361752 0.90106673
  0.49344254 0.8969664  0.4496558  0.34959811 0.77552379 0.9170979
  0.99540694 0.45390997 0.73322771 0.33032953 0.35507562 0.32243219
  0.54643009 0.32988901]
 [0.39278759 0.47521298 0.08354901 0.1616909  0.87815775 0.91889701
  0.52554578 0.65207962 0.83281761 0.06809308 0.51179752 0.90199937
  0.79334799 0.77948096 0.317143   0.2184021  0.20752125 0.87901878
  0.51463407 0.29994607]
 [0.75678418 0.70809226 0.54627415 0.86512399 0.83882988 0.86758821
  0.75643645 0.365

In [ ]:
# Transposing for matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])
product = A.dot(B.transpose())  # Transposing B to make multiplication possible

print(product)